### ISSUE TITLE
How can I merge the ceo bug into ocp

### ISSUE THREAD

**Issue by lance5890** [openshift/cluster-etcd-operator#1000]
I have found two ceo bug when I intall ocp release

1. When install SingleNodeTopology ocp release, the etcd env miss ETCD_URL_HOST , ETCD_NAME , and lead to single mode failed occasionally
2. When install HABootstrapScaling ocp relesase, when I remove one master node ,the ceo will stuck in etcd memer list about 15 minutes

I have resolved this two issue , I would like to merge my code into ceo for you review

@tjungblu @hexfusion

**Comment by tjungblu** [comment]
Sounds great, can you send us a pull request?

**Comment by lance5890** [comment]
these two bugs have all merged into master, i will close this issue
