### ISSUE TITLE
The etcd restart too often (compared to kubeadm installation method)

### ISSUE THREAD

**Issue by lance5890** [openshift/cluster-etcd-operator#1031]
1. I found the etcd restart too often ,compared to kubeadm installation method
2. Maybe this has something to do with the health check , in the ocp, the health check is conducted by the ceo func,

I will complete this issue when I found more evidence

**Comment by lance5890** [comment]
@Elbehery @tjungblu

**Comment by Elbehery** [comment]
Thanks @lance5890 for filling this 

Please give us more details whenever possible :)

**Comment by lance5890** [comment]
1. By the kubeadm installation, the etcd health check is conducted as follows, which use the localhost 2381 metrics port as the health check :
<img width="193" alt="image" src="https://user-images.githubusercontent.com/30207518/227466129-48b8cd06-4d0b-4163-b684-76af6856b672.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/30207518/227466337-cb949890-5dac-4633-9898-966f599e6d9c.png">

2. But in the ocp installation, the etcd health check is conducted by the etcd-health-monitor, which use the WithQuorumRead func to check the etcd health as follows:

https://github.com/openshift/cluster-etcd-operator/blob/7a8db9c7132dd171a3a9fd31504cedffc1ea5af5/pkg/cmd/monitor/monitor.go#L161-L171

3. The ocp use etcd QuorumRead to check the etcd health is very heavy operation, as we all now, the etcd quorum is Linearizable，it is heavily dependent on cluster performance 
4. If the ocp cluster use hdd disk(not the ssd), and the health check will fail too often, and in this time , restart the etcd will exacerbate cluster instability

**Comment by lance5890** [comment]
Maybe we should use the light way to check the etcd health , but not depend on the cluster performance  @Elbehery @tjungblu

**Comment by Elbehery** [comment]
any updates here ?

**Comment by lance5890** [comment]
> any updates here ?

the ocp etcd health check is conducted by too heavy, compared to the metrics way by the kubeadm

**Comment by Elbehery** [comment]
@lance5890  to make this decision we need some performance proofs imho 

cc @tjungblu @hasbro17 @dusk125

**Comment by lance5890** [comment]
as release 4.12 has no health-monitor container any more, i will close this issue and check
