### ISSUE TITLE
clustermembercontroller2: steps for the controller

### ISSUE THREAD

**Issue by alaypatel07** [openshift/cluster-etcd-operator#105]
Because of the way etcd membership works, it is a good practice (and in this case a requirement) to scale up only one member at a time[1]. Hence the implementation would be as follows:

1. List all the static pods in etcd namespaces
2. List the members of etcd cluster membership
3. if any one of the members from etcd membership list is unhealthy, do nothing, return.
4. if all the etcd members are running healthy, pick a static pod that is not ready yet and not already a part of the etcd membership, and add it to the cluster membership.

[1]. https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member

> If adding multiple members the best practice is to configure a single member at a time and verify it starts correctly before adding more new members. If adding a new member to a 1-node cluster, the cluster cannot make progress before the new member starts because it needs two members as majority to agree on the consensus. This behavior only happens between the time etcdctl member add informs the cluster about the new member and the new member successfully establishing a connection to the existing one.

**Comment by deads2k** [comment]
Questions and comments

1. How will you get the first connection to the bootstrap etcd member?
2. Make a note that we need a controller that reads the etcd cluster membership and reports degraded if any one of the members is unhealthy.
3. It needs to be a static pod that is not already in the membership list.
4. You need to separate the logic that decides if it is safe to remove the bootstrap node to a distinct operator.  We can see now that it is a logically distinct operation.

**Comment by alaypatel07** [comment]
> How will you get the first connection to the bootstrap etcd member?

There are a couple of options, using the storageURLs in etcd CR and `host-etcd` endpoint resource. #98 takes care of preserving etcd-bootstrap if it exists in `host-etcd`. Since `host-etcd` is built directly from etcd membership, I planned on using that to get the first connection to the bootstrap etcd member.

> Make a note that we need a controller that reads the etcd cluster membership and reports degraded if any one of the members is unhealthy.
> You need to separate the logic that decides if it is safe to remove the bootstrap node to a distinct operator. We can see now that it is a logically distinct operation.

Will create issues for these.

> It needs to be a static pod that is not already in the membership list.
Updated the original steps with this.
