### ISSUE TITLE
wait for membership command: steps in bash

### ISSUE THREAD

**Issue by alaypatel07** [openshift/cluster-etcd-operator#106]
Assuming ALL_CLUSTER_MEMBERS env variable has a list of all the members to be scaled, the bash version of [this](https://github.com/openshift/cluster-etcd-operator/pull/103/files#diff-f19a648fa992d810479d30657e849c6dR27-R29) in my mind would be as follows:

```
$ IS_MEMBER_ADDED=$(etcdctl --endpoints=$ALL_CLUSTER_MEMBERS member list | grep ${NODE_NAME}.*:2380)
$ if [ -z "$IS_MEMBER_ADDED" ]; then 
    $INITIAL_CLUSTER=$(etcdctl --endpoints=$ALL_CLUSTER_MEMBERS member list | cut -d',' -f4  | xargs | sed -e 's/ /,/g'; export $INITIAL_CLUSTER;
done
```

All_CLUSTER_MEMBERS here would be something like `https://member1:2379,https://member2:2379,https://member3:2379,https://10.0.0.4:2379`.

/cc @deads2k

**Comment by deads2k** [comment]
@sttts how can we take something like that only if the member isn't present (that first line I think), we try every second for thirty seconds.  If it's not found after 30 seconds of trying, we exit non-zero from the bash script.

This is needed as a pre-step to safely start etcd.  We want it in the "real" container because if we crashloop I'm sure init containers run again.

**Comment by retroflexer** [comment]
@deads2k, @sttts, @alaypatel07  
This worked for me (assuming ALL_CLUSTER_MEMBERS and NODE_NAME are properly set):
```
COUNT=30
while [ $COUNT -gt 0 ]; do
	IS_MEMBER_ADDED=$(etcdctl --endpoints="${ALL_CLUSTER_MEMBERS}" member list | grep -o "${NODE_NAME}\..*:2380")
	if [ ! -z "${IS_MEMBER_ADDED}" ]; then
		break
	fi
	sleep 1
	let COUNT=$COUNT-1
done

# if the member is not added in 30 seconds
if [ -z "$IS_MEMBER_ADDED" ]; then
	echo "member ${NODE_NAME} is not added in 30 seconds"
	exit 1
fi

export INITIAL_CLUSTER=$(etcdctl --endpoints=$ALL_CLUSTER_MEMBERS member list | awk -F'[, ]' '{ print $7 }'  | paste -sd ",")
echo $INITIAL_CLUSTER
```

**Comment by hexfusion** [comment]
Why would we not do this logic in go? We have much tighter control of error reporting, log levels etc.

**Comment by deads2k** [comment]
> Why would we not do this logic in go? We have much tighter control of error reporting, log levels etc.

because your image doesn't appear to be built from a repo that lets us inject more binaries into it.

**Comment by hexfusion** [comment]
> because your image doesn't appear to be built from a repo that lets us inject more binaries into it.

Could it not be a command of our binary `cluster-etcd-operator check-membersip --foo`

**Comment by deads2k** [comment]
> Could it not be a command of our binary `cluster-etcd-operator check-membership --foo`
> 
> [#103 (comment)](https://github.com/openshift/cluster-etcd-operator/pull/103#discussion_r377181679)

It needs to set an env var in the container running etcd. As much as I hate bash, I hate having containers pass state around via files on disk even more.

**Comment by deads2k** [comment]
> > Could it not be a command of our binary `cluster-etcd-operator check-membership --foo`
> > [#103 (comment)](https://github.com/openshift/cluster-etcd-operator/pull/103#discussion_r377181679)
> 
> It needs to set an env var in the container running etcd. As much as I hate bash, I hate having containers pass state around via files on disk even more.

Add a binary in the etcd image and you're on.
