### ISSUE TITLE
manifests: bump loglevel of operator to normal

### ISSUE THREAD

**Issue by lance5890** [openshift/cluster-etcd-operator#1061]
1. The loglevel has no effect anymore, as follows:  https://github.com/openshift/cluster-etcd-operator/blob/d7d5425f8ed55721bb57adf1867dd2e31989c19c/manifests/0000_20_etcd-operator_06_deployment.yaml#LL48C14-L48C14 
<img width="502" alt="image" src="https://github.com/openshift/cluster-etcd-operator/assets/30207518/a69e9a2b-9bd4-4bb9-bf68-c649d0891539">

2. As the operator log level is set by the operator.sepc.operatorLogLevel, which was controlled by the "NewClusterOperatorLoggingController"

3. we should remove the redundant options and obfuscation in ceo, just as the KAS-o has removed the line in  https://github.com/openshift/cluster-kube-apiserver-operator/blob/a1de1b1cc85ce2d41e918d14534e5187b981819b/manifests/0000_20_kube-apiserver-operator_06_deployment.yaml#L48

**Comment by tjungblu** [comment]
thanks @lance5890. I think this is still in use from:

https://github.com/openshift/cluster-etcd-operator/blob/master/cmd/cluster-etcd-operator/main.go#L42

and the help text mentions you can set it:

```
OpenShift cluster etcd operator

Usage:
  cluster-etcd-operator [flags]
  cluster-etcd-operator [command]

Available Commands:
  cert-syncer     
  cluster-backup  Backs up a snapshot of etcd database and static pod resources to a given directory
  cluster-restore Restores a cluster backup from a given directory
  completion      Generate the autocompletion script for the specified shell
  help            Help about any command
  installer       Install static pod and related resources
  monitor         Performs periodic health checks and logs service status
  operator        Start the Cluster etcd Operator
  prune           Prune static pod installer revisions
  readyz          Serve the HTTP /readyz endpoint health check for an etcd member
  render          Render etcd bootstrap manifests, secrets and configMaps
  verify          performs checks to verify preconditions and exit 0 on success
  wait-for-ceo    waits for cluster-etcd-operator to finish bootstrap etcd cluster

Flags:
  -h, --help                           help for cluster-etcd-operator
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
  -v, --v Level                        number for the log level verbosity
      --vmodule moduleSpec             comma-separated list of pattern=N settings for file-filtered logging (only works for the default text log format)

```

The code path you cite goes through the -v flag too:
https://github.com/openshift/library-go/blob/master/pkg/operator/loglevel/util.go#L71-L76

**Comment by lance5890** [comment]
> thanks @lance5890. I think this is still in use from:
> 
> https://github.com/openshift/cluster-etcd-operator/blob/master/cmd/cluster-etcd-operator/main.go#L42
> 
> and the help text mentions you can set it:
> 
> ```
> OpenShift cluster etcd operator
> 
> Usage:
>   cluster-etcd-operator [flags]
>   cluster-etcd-operator [command]
> 
> Available Commands:
>   cert-syncer     
>   cluster-backup  Backs up a snapshot of etcd database and static pod resources to a given directory
>   cluster-restore Restores a cluster backup from a given directory
>   completion      Generate the autocompletion script for the specified shell
>   help            Help about any command
>   installer       Install static pod and related resources
>   monitor         Performs periodic health checks and logs service status
>   operator        Start the Cluster etcd Operator
>   prune           Prune static pod installer revisions
>   readyz          Serve the HTTP /readyz endpoint health check for an etcd member
>   render          Render etcd bootstrap manifests, secrets and configMaps
>   verify          performs checks to verify preconditions and exit 0 on success
>   wait-for-ceo    waits for cluster-etcd-operator to finish bootstrap etcd cluster
> 
> Flags:
>   -h, --help                           help for cluster-etcd-operator
>       --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
>   -v, --v Level                        number for the log level verbosity
>       --vmodule moduleSpec             comma-separated list of pattern=N settings for file-filtered logging (only works for the default text log format)
> ```
> 
> The code path you cite goes through the -v flag too: https://github.com/openshift/library-go/blob/master/pkg/operator/loglevel/util.go#L71-L76

set the --v=4 has no effect when the operator.spec.operatorLogLevel = Normal, and we could change the operator log level by operator.spec.operatorLogLevel , not by change the deployment config

**Comment by lance5890** [comment]
and set --v=4 is inappropriate， u can see the https://github.com/openshift/cluster-kube-apiserver-operator/commit/a11f2d4d49d8de528a40c1b19fd475bd4fac610a

**Comment by tjungblu** [comment]
what do you mean with "inappropriate"? If it's not necessary we should remove it from the cmdline flags, too.

**Comment by lance5890** [comment]
> what do you mean with "inappropriate"? If it's not necessary we should remove it from the cmdline flags, too.

firstly ,is maybe set to --v=2, which is normal Log level; secondly, the --v=4 is not working at all, the operator log shows by the operator.spec.operatorLogLevel, not by the --v=4

**Comment by lance5890** [comment]
> what do you mean with "inappropriate"? If it's not necessary we should remove it from the cmdline flags, too.

--v flag does work , but in the staticpod controller and operator operatorLogLevel func, it could be remove in the deployment config, as u change the --v will restart the deploy , but if u change the operatorLogLevel , it will display logs in real time, and wil not restart the ceo

**Comment by lance5890** [comment]
Maybe the title of this issue maybe "bump loglevel of operator to normal"
