### ISSUE TITLE
bootstrap_teardown_controller should not run if bootstrap node does not exist

### ISSUE THREAD

**Issue by hexfusion** [openshift/cluster-etcd-operator#107]
Lots of these messages in logs. But we seem to continue logging even if bootstrap node is not longer in the cluster.

> 0207 23:45:47.542000       1 bootstrap_teardown_controller.go:253] etcd is available, bootstrap complete

I know things are being updated soon but just to track.

cc @alaypatel07

**Comment by hexfusion** [comment]
Same here

> I0207 23:45:33.093922       1 clustermembercontroller.go:238] scaling complete, etcd-bootstrap is safe to remove

The logging seems to assume bootstrap is relevant through the life of the cluster.

**Comment by deads2k** [comment]
@hexfusion we should keep running the controller because it's forcing a level.  Every time you start this binary it will run the check, "is the bootstrap there", so the idea that it isn't a controller is flawed.

However, we shouldn't have useless spam messages.  @alaypatel07 push the spam to v4.

**Comment by hexfusion** [comment]
Sounds good logging is confusing during upgrade so as long as we make this sane.
