### ISSUE TITLE
docs: update FAQ

### ISSUE THREAD

**Issue by hexfusion** [openshift/cluster-etcd-operator#23]

**Comment by warmchang** [comment]
Hi, what's the different between [cluster-etcd-operator](https://github.com/openshift/cluster-etcd-operator) and [etcd-operator by coreos](https://github.com/coreos/etcd-operator)?

**Comment by hexfusion** [comment]
@warmchang basically this operator manages the cluster etcd or etcd that k8s runs on. etcd-operator is for managing etcd on top of Kubernetes.
