### ISSUE TITLE
DR bug: theory and proposed solution 

### ISSUE THREAD

**Issue by alaypatel07** [openshift/cluster-etcd-operator#278]
The DR scenario was created by stopping two machines, the backed up data was at revision 4. After restore pods runs the control plane is up with a single master node. Revision 4 has the three nodes(1 running other two terminated) env variables that were from backup time. New nodes are created using machine API. Two new revisions are created, revision 5 and 6. Revision 5 still has old data, revision 6 has new nodes data. A pod on the new node is created with revision 5. Since it has old node data, it is not able to find the correct NODE_NODE_ENVVAR and it crashloops. This leads to full-blown outage.

In order to save CEO from this scenario I am proposing of doing the following:
1. Add the list of nodes at the time revision was created in the revision itself. Create a new configmap `nodes-<revision-number>`
2. Use the pod mutation function to get `nodes-<revision-number>` and check if the node that the installer is run on belongs to the list of the nodes in configmap. If not, this revision is not usable for the node override the `pod.Command` of the installer pod with `echo "This revision does not include the node"; exit 1` . 

This will make sure that the new nodes does not have a static pod with faulty older revision and skip to the latest available revisions

**Comment by hexfusion** [comment]
```
      {
        "lastTransitionTime": "2020-03-25T12:50:07Z",
        "message": "NodeInstallerProgressing: 2 nodes are at revision 0; 1 nodes are at revision 3; 0 nodes have achieved new revision 5",
        "reason": "NodeInstaller",
        "status": "True",
        "type": "Progressing"
      },
      {
        "lastTransitionTime": "2020-03-25T12:00:34Z",
        "message": "StaticPodsAvailable: 1 nodes are active; 2 nodes are at revision 0; 1 nodes are at revision 3; 0 nodes have achieved new revision 5\nEtcdMembersAvailable: ip-10-0-131-16.us-west-1.compute.internal members are available,  have not started,  are unhealthy,  are unknown",
        "reason": "AsExpected",
        "status": "True",
        "type": "Available"
      },
```

**Comment by alaypatel07** [comment]
@hexfusion yes, the cluster I was looking at had rev numbers 4, 5, and 6 instead of 3,4 and 5 like in the example you shared.

I think what happens is that since a node is on rev 3,  static pod controller tries to make sure all nodes are on rev 3. The new nodes cannot run until rev 5. Hence we need to make sure that the revision contains the list of nodes they are supposed to run on, which is in line with the proposed solution
