### ISSUE TITLE
clusterleadercontroller: minimize disruptions during install and upgrade

### ISSUE THREAD

**Issue by hexfusion** [openshift/cluster-etcd-operator#285]
Various times during the life of a cluster we create a leader election during normal operation. an example of such an event is an upgrade. During upgrade it is inevitable that the leader will be restarted as we roll node by node. But etcd can control who is leader and if we could also observe the order in which these nodes reboot we could transfer leadership before the node is restarted.

Another example of disruption we could control is install. Because the bootstrap etcd instance is the first etcd that is started there is a good chance that when we remove this member that we also remove the leader. As we know the leaders member ID it should be fairly trivial to make sure before we remove bootstrap from the cluster that it is not the leader.

Also for performance reasons we don't want etcd on bootstrap to be the leader. Its disks are often underpowered and should not take the load of leader. The faster we can transfer leadership the better.

ref: https://github.com/etcd-io/etcd/blob/release-3.3/clientv3/maintenance.go#L227

**Comment by wking** [comment]
> But etcd can control who is leader and if we could also observe the order in which these nodes reboot we could transfer leadership before the node is restarted.

Bonus points if you can proactively hand off the leader role to the youngest control-plane node, because that's the least likely to be the next one to reboot ;).

**Comment by hexfusion** [comment]
Also wanted to add after listening to @alaypatel07 talk about an issue that he was having. It is basically borderline dangerous to push a new revision without this. Every revision bump WILL cause leader election. This is unacceptable.
