### ISSUE TITLE
switch leader if MCO is going to reboot a node 

### ISSUE THREAD

**Issue by cgwalters** [openshift/cluster-etcd-operator#392]
Moving this from https://github.com/openshift/machine-config-operator/issues/1897#issuecomment-658923552

I am an etcd/raft novice, but it would seem to make sense to me for the MCO and CEO to communicate and for the CEO to notice the MCO is in the process of draining/rebooting a node and to be sure that the node being upgraded at least isn't the leader.

Detecting "node will be upgraded" could be implemented today in CEO by watching the `currentConfig` and `desiredConfig` annotations - if they are different that's what the MCO will react to.

Alternatively, the MCD could explicitly notice the case when it's on a control plane node and signal etcd directly.

**Comment by hexfusion** [comment]
related: https://github.com/openshift/cluster-etcd-operator/issues/285

**Comment by cgwalters** [comment]
Upon further reflection, I think we really want to this [the other way around](https://github.com/openshift/machine-config-operator/issues/1897#issuecomment-658965838).
