### ISSUE TITLE
Check the validity of certificates

### ISSUE THREAD

**Issue by retroflexer** [openshift/cluster-etcd-operator#487]
Currently cert-signer controller only checks for the presence of the secrets but doesn't validate it.

What if:

- the secret is missing either the cert or the key?
- the cert and/or key can't be parsed
- the cert and key are not related?

It may be useful to create the validation of secrets as a utility function and move it to library-go for a wider adoption.

**Comment by hexfusion** [comment]
@marun can this be closed?
