### ISSUE TITLE
Allow configuration of heartbeat and election timeouts

### ISSUE THREAD

**Issue by ahus1** [openshift/cluster-etcd-operator#499]
**Current Situation:**
Currently the heartbeat and election timeouts are hard coded and can not be changed depending on the environment. 
ETCD_HEARTBEAT_INTERVAL is set to 100 and ETCD_ELECTION_TIMEOUT is set to 1000 (except on Azure). 

**Why this is needed:**
In our environment we see a lot of leader changes due to latencies.
Reading the manuals of etcd, [etcd recomments tuning these settings](https://github.com/etcd-io/etcd/blob/master/Documentation/tuning.md). 
Currently #221 is not implemented and there is no expected date for this. 

**How this could behave:**
An admin could add the settings to _etcd-operator-config_ to configure these values.

**Comment by cloudbustinguk** [comment]
Multiple customers of mine would benefit from this.

I've come to call it the "VIP Flip of Death", for upon having a leader change, it's often the case that the node bidding farewell to the VIP, will end up `NotReady`.

**Comment by williamcaban** [comment]
This option is required for optimizing control plane deployments when deploying control planes across diffrent subnets.

A similar request is part of RFE-1091 (https://issues.redhat.com/browse/RFE-1091)

**Comment by hexfusion** [comment]
cluster-etcd-operator should autotune[1] these runtimes in response to observed conditions.

[1] https://issues.redhat.com/browse/ETCD-121

**Comment by ahus1** [comment]
Unfortunately I can't access any of the issues linked above, therefore I'm unable to track any progress on this.

As a (desperate) measure we did the following in our development environment: we patched the file `/etc/kubernetes/manifests/etcd-pod.yaml` on each master node with custom, prolonged values for   ETCD_HEARTBEAT_INTERVAL  and ETCD_ELECTION_TIMEOUT via the shell into each master node.

After each OpenShift update we would repeat the procedure as the changes would be lost on OpenShift upgrades. 

(If you want to try something like this, this will probably void your warranty. Use at your own risk.)

**Comment by tjungblu** [comment]
@ahus1 I've opened the RFE again for debate. Since most of you folks are at RedHat, could you kindly connect on that [RFE](https://issues.redhat.com/browse/RFE-1091) as well? JIRA allows you to login with SSO and the RFE project should be open to everyone on the internet even.

I don't think anyone actually monitors the issues here and fighting with the stale bot is surely a losing battle :)
