### ISSUE TITLE
cluster requires manual step to recover after deleting `openshift-etcd` ns

### ISSUE THREAD

**Issue by sallyom** [openshift/cluster-etcd-operator#513]
Cluster should recover after deleting operand ns, but upon deleting the `openshift-etcd` ns, it is restored via CVO but this configmap is missing: https://github.com/openshift/cluster-etcd-operator/blob/master/bindata/bootkube/manifests/00_etcd-endpoints-cm.yaml. Cluster recovers only after manually applying this file.

**Comment by hexfusion** [comment]
cc @ironcladlou
