### ISSUE TITLE
The operator leaks one tcp connection every minute when thanos is queried

### ISSUE THREAD

**Issue by webner** [openshift/cluster-etcd-operator#533]
Every time thanos is called a new Transport object is created which is not automatically garbage collected. This leads to one new established connection to thanos every minute. After a couple of days there are too many connections open and every call to thanos fails.

```
sh-4.4# echo "$(date) $(lsof -i@thanos-querier.openshift-monitoring | wc -l)"
Thu Jan 21 07:35:48 UTC 2021 2648
sh-4.4# echo "$(date) $(lsof -i@thanos-querier.openshift-monitoring | wc -l)"
Thu Jan 21 07:47:00 UTC 2021 2659


sh-4.4# lsof -i@thanos-querier.openshift-monitoring   
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
cluster-e   1 root    7u  IPv4 298971301      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:37812->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root    9u  IPv4 298977977      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:38932->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   10u  IPv4 298955389      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:36646->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   12u  IPv4 298994848      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:41130->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   14u  IPv4 298984365      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:40036->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   15u  IPv4 299011221      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:43426->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   16u  IPv4 299016066      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:44610->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   17u  IPv4 299003018      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:42306->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
cluster-e   1 root   18u  IPv4 299052787      0t0  TCP etcd-operator-6bf9f6ff46-7kq42:49186->thanos-querier.openshift-monitoring.svc.cluster.local:xmltec-xmlmail (ESTABLISHED)
...

```

There is an old open issue in net/http for this here: https://github.com/golang/go/issues/24739

Consider reusing the same Transport object or closing the idle connections in a deferred function.
https://github.com/openshift/cluster-etcd-operator/blob/668c44fabd967a50d4ddd5082a54409dc9c1e21f/pkg/operator/metriccontroller/client.go#L52

**Comment by retroflexer** [comment]
The options to fix the leak are:
 the options to improve this are:

1. Set Transport.DisableKeepAlives=true when setting up the transport (bad for places where we want to make several requests before discarding the client, which is pretty much everywhere)
2. Call Transport.CloseIdleConnections after we're done with a client (hard to plumb through access after the transport has been wrapped 4-5 times (for debugging, custom wrapping, bearer/basic auth, and user agent header-setting), sometimes hard to know when we're done with a client
3. Avoid constructing lots of identical http.Transport objects. If lots of throwaway clients are built with different TLS options, we can still see growth, but this will drastically help the "client per user verification" case

@ironcladlou implemented 2nd option here: https://github.com/openshift/online/blob/eb52686e6b8d7db0eee092212dce4f6b603d3425/user-analytics/vendor/github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp/cleanhttp.go
