### ISSUE TITLE
EtcdCertSignerController_Error due to secondary interface (added later)

### ISSUE THREAD

**Issue by vishnoisuresh** [openshift/cluster-etcd-operator#575]
**Context:** 
Cluster was deployed as UPI on Vsphere cluster.
Current version is 

**oc version**
`
Client Version: 4.7.0-202104142050.p0-95881af
Server Version: 4.7.8
Kubernetes Version: v1.20.0+7d0a2b2
`

**Current Situation:** 
Cluster Etcd Operator (CEO) is in degraded phase, due to adding a secondary IP address to the rhel coreos. (using nmstate operator).   I am receiving the following message from the CEO.

`
EtcdCertSignerControllerDegraded: [SAN for the certificate etcd-peer-dexxxxxxxx.internal.knu does not include 192.168.197.6: x509: certificate is valid for 10.61.59.11, not 192.168.197.6, SAN for the certificate etcd-serving-dexxxsl3571.internak.knu does not include 192.168.197.6: x509: certificate is valid for ::1, 10.61.59.11, 127.0.0.1, ::1, not 192.168.197.6, SAN for the certificate etcd-serving-metrics-dexxxxxxxxxx.internal.knu does not include 192.168.197.6: x509: certificate is valid for ::1, 10.61.59.11, 127.0.0.1, ::1, not 192.168.197.6
`
I would like to know,  
- Should I  modify the certs  ? 
- Should I  remove the certs so CEO can regenerate them ?
- is there How to for this issue ?

**Comment by hexfusion** [comment]
etcd-operator uses InternalIP of node to define SAN.

what does are the output of 
```
oc get node <node> -o json | jq '.status.addresses'
```
```
oc get nodes -o wide
```

**Comment by vishnoisuresh** [comment]
@hexfusion  thanks for response, here are the output of the commands.  I needed to add secondary IP for the storage purpose.  

```
oc get node dexxxsl3571.int.kn -o json | jq '.status.addresses'
[
  {
    "address": "10.61.59.11",
    "type": "ExternalIP"
  },
  {
    "address": "192.168.197.6",
    "type": "ExternalIP"
  },
  {
    "address": "10.61.59.11",
    "type": "InternalIP"
  },
  {
    "address": "192.168.197.6",
    "type": "InternalIP"
  },
  {
    "address": "dexxxsl3571.int.kn",
    "type": "Hostname"
  }
]
```


```
$ oc get nodes -owide
NAME                   STATUS   ROLES    AGE    VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                       KERNEL-VERSION                 CONTAINER-RUNTIME
cp-c1d-compute-4fldj   Ready    worker   3d7h   v1.20.0+7d0a2b2   10.61.59.48   10.61.59.48   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
cp-c1d-compute-9ldp6   Ready    worker   3h5m   v1.20.0+7d0a2b2   10.61.59.41   10.61.59.41   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
cp-c1d-compute-wpf7g   Ready    worker   4d2h   v1.20.0+7d0a2b2   10.61.59.42   10.61.59.42   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl3569.internal.knu     Ready    worker   424d   v1.20.0+7d0a2b2   10.61.59.16   10.61.59.16   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl3570.internal.knu     Ready    master   424d   v1.20.0+7d0a2b2   10.61.59.12   10.61.59.12   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl3571.internal.knu     Ready    master   424d   v1.20.0+7d0a2b2   10.61.59.11   10.61.59.11   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl4086.internal.knu     Ready    worker   170m   v1.20.0+7d0a2b2   10.61.59.17   10.61.59.17   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl4087.internal.knu     Ready    worker   175m   v1.20.0+7d0a2b2   10.61.59.18   10.61.59.18   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl2328.internal.knu     Ready    worker   424d   v1.20.0+7d0a2b2   10.61.59.15   10.61.59.15   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl2329.internal.knu     Ready    worker   424d   v1.20.0+7d0a2b2   10.61.59.14   10.61.59.14   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8
dexxxsl2330.internal.knu     Ready    master   424d   v1.20.0+7d0a2b2   10.61.59.13   10.61.59.13   Red Hat Enterprise Linux CoreOS 47.83.202104161442-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-6.rhaos4.7.gitf1d5201.el8

```

**Comment by hexfusion** [comment]
@marun thoughts?

**Comment by marun** [comment]
@hexfusion In 4.7, only missing secrets will [prompt certificate recreation](https://github.com/openshift/cluster-etcd-operator/blob/release-4.7/pkg/operator/etcdcertsigner/etcdcertsignercontroller.go#L110).

Without a way to detect node changes, any discrepancy between node internal addresses and the SANs of certificates for that node is presumed to represent a potential membership change requiring manual intervention.

I've cherry-picked the validation improvements introduced in #540 to 4.7, looks clean: https://github.com/openshift/cluster-etcd-operator/pull/577

**Comment by marun** [comment]
@vishnoisuresh Pending the backport linked in my previous comment, your fix is to trigger certificate replacement by deleting one cert secret for each node. I suggest removing `openshift-etcd/etcd-serving-metrics-*`. The operator will be prompted by the absence of these certificates to recreate all etcd certificates.

**Comment by vishnoisuresh** [comment]
@marun Yea, I can verify that after deleting both of the certs `openshift-etcd/etcd-serving-metrics-*` and `openshift-etcd/etcd-peer-*` . New certs has been created which include the secondary IP in SAN list. 

@hexfusion  @marun Thanks for prompt remediation. :)   
Nevertheless, I will go though the docs https://github.com/openshift/cluster-etcd-operator/blob/master/docs/etcd-tls-assets.md  few more times to understand the mesh of TLS
