### ISSUE TITLE
Backport #603 to 4.6

### ISSUE THREAD

**Issue by kalexand-rh** [openshift/cluster-etcd-operator#623]
This documentation bug [1] requests a step to manually verify the health of the etcd database snapshot. This was fixed in code on #603. @hexfusion says that it's possible to apply this change to a 4.6 release but would require manual intervention.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1846118

**Comment by hexfusion** [comment]
thanks for the reminder PR is up @kalexand-rh
