### ISSUE TITLE
fsync controller will report false positives if metrics are missing

### ISSUE THREAD

**Issue by hexfusion** [openshift/cluster-etcd-operator#673]
https://bugzilla.redhat.com/show_bug.cgi?id=2008175

```
increase((max by (job) (etcd_server_leader_changes_seen_total) or 0*absent(etcd_server_leader_changes_seen_total))[5m:1m])
```

green line is leader elections observed which is flat.

![image](https://user-images.githubusercontent.com/1249749/134918692-43ca6cf0-4fb0-4ee3-8735-f5d035d56170.png)

Below clearly shows the gaps in collection
![image](https://user-images.githubusercontent.com/1249749/134919312-f62591ee-57df-41de-a313-545e207d89ad.png)

**Comment by hexfusion** [comment]
cc @lilic

**Comment by lilic** [comment]
@hexfusion I will have a look if I can adjust the query.
