### ISSUE TITLE
things to fix

### ISSUE THREAD

**Issue by deads2k** [openshift/cluster-etcd-operator#80]
- [x] outdated go mod @deads2k - https://github.com/openshift/cluster-etcd-operator/pull/79
  - [x] stuck on old mco @deads2k - https://github.com/openshift/cluster-etcd-operator/pull/79
  - [x] stuck on skewed etcd @deads2k - https://github.com/openshift/cluster-etcd-operator/pull/78
- [x] non-controller based bootstrap removal @alaypatel07 - https://github.com/openshift/cluster-etcd-operator/pull/63
- [x] old operator client @retroflexer @sanchezl https://github.com/openshift/cluster-etcd-operator/pull/86
- [x] old copy of status condition union @sanchezl  https://github.com/openshift/cluster-etcd-operator/pull/81
- [ ] authentication as SA token, switch to cert  - @deads2k
  - [ ] installer cert based kubeconfig - @deads2k https://github.com/openshift/installer/pull/3057
  - [ ] proof that we can plumb this client cert through @hexfusion
- [ ] remove any obedience of being unmanaged.  We are always managed.  @retroflexer https://github.com/openshift/cluster-etcd-operator/pull/89
- [ ] separate progressing and available decisions
  - [ ] let's get control loops listed here. @alaypatel07 
  - [ ]  clustermembercontroller @alaypatel07 
  - [ ] configobservation @retroflexer 
  - [ ] etcdcertsigner
  - [ ] hostendpointcontroller @sanchezl 
- [x] fix the build to use the normal machinery. @tnozicka 
- [x] bring in the static pod operator controllers. @deads2k - https://github.com/openshift/cluster-etcd-operator/pull/88
  - [x] static pod controllers are setting global conditions @deadsk2 https://github.com/openshift/library-go/pull/704 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/754
- [ ] events versus info messages.  messages go away with logs, events last "forever" for our CI use-cases.
- [ ] create struct and schema for the observedConfig.  There appears to be a significant structure there
- [ ] image stream references for etcd images are missing @sanchezl https://github.com/openshift/cluster-etcd-operator/pull/90
- [x] stop setting global conditions @deads2k https://github.com/openshift/cluster-etcd-operator/pull/91
- [ ] simplify host endpoint controller to five direct steps @sanchezl 
    1. list all static pods in the openshift-etcd namespace
    1. filter the list to only those which are the etcd port
    1. filter that list to the set that are ready
    1. confirm expected etcd membership using the etcd API
    1. use this list of static pods to write the endpoints
- [ ] start collecting the required values for a static pod. @deads2k
- [ ] create a new daemonset that reads the required certificates, keys, and ca bundles and if they are present on disk and not in-cluster, pushes the into the cluster. We need this for migration. @deads2k
     1. this pre-supposes that etcd doesn't care *which* cert/key is used and we can use the same ones for all etcds.  this is similar to using the one set of credentials for all kube-controller-managers
- [ ] make sure that the installer produces all the etcd trust required.  then update the render command to create the required certificates, keys, and ca bundles in the cluster.
- [ ] update the static pod created by the operator to use the certificates, keys, and ca bundles from the the cluster, not the ones on disk.
- [ ] Start writing a new controller that 
     1. observes the static pods on the masters
     2. queries etcd to figure out which peers it expects
     3. if one static pod is on the master, is unready, and is not in the peer list, then the controller adds the member to etcd directly.

**Comment by alaypatel07** [comment]
List of controllers for fixing status conditions:

- [ ] clustermembercontroller
- [ ] configobservation
- [ ] etcdcertsigner
- [ ] hostendpointcontroller

Cant edit the issue, so listing as comment @deads2k
