### ISSUE TITLE
Can I override the ETCD_QUOTA_BACKEND_BYTES value ?

### ISSUE THREAD

**Issue by Shikaz** [openshift/cluster-etcd-operator#946]
How can I increase quota by overriding the ETCD_QUOTA_BACKEND_BYTES and/or --quota-backend-bytes= value ?
I can see that it's part of FixedEtcdEnvVars func in the code, not sure if this can be modified by
patching the etcd cluster and pass the value as an env variable.

When updating the etc-pod configmap it does not reflect to the etcd pods even when i edit the etcd cluster with unsupportedConfigOverrides

https://github.com/openshift/cluster-etcd-operator/blob/17238fb25a3e14d0ef123f26e4070a2673315eb8/pkg/etcdenvvar/etcd_env.go#L35

**Comment by tjungblu** [comment]
hey @Shikaz. 
We're not actively monitoring the issues here, but your ask has already been filed here: https://issues.redhat.com/browse/RFE-1969

It can't be modified currently through the operator.
