### ISSUE TITLE
Master DR scenario (replacing a missing master node) does not work because of quorumChecker.IsSafeToUpdateRevision

### ISSUE THREAD

**Issue by mbalazs** [openshift/cluster-etcd-operator#994]
There is a DR procedure described in the OpenShift manual for [replacing an unhealthy etcd member](https://docs.openshift.com/container-platform/4.12/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-etcd-member_replacing-unhealthy-etcd-member) after a master node's machine has been erased completely and reprovisioned.

This procedure works fine on OCP 4.9, but does not work on OCP 4.10 or 4.11. The outline of the steps to reproduce the problem is the following:

1. Install an OCP cluster with UPI on VMware
2. Remove one of the master node VMs from VMware
3. Reprovision the VM by cloning from the CoreOS image with proper ignition configs, and wait for it to join the cluster.
4. Follow the steps described under section "Replacing an unhealthy etcd member whose machine is not running or whose node is not ready" to redeploy the etcd instance and other control plane pods on the newly joined master.
5. Wait until all clusteroperators are working properly.

The issue is, that from OCP 4.10 onwards, the etcd operator does not generate the static pod definition for etcd on the new master because the quorumChecker.IsSafeToUpdateRevision method will not allow to update the static pod definitions when there are only 2 etcd members. I have reached this conclusion based on the error messages of the etcd operator logs (I don't have the logs anymore unfortunately), and by analyzing the source code of the operator. Also by looking at the source code I have discovered that those checks can be disabled by setting the "useUnsupportedUnsafeNonHANonProductionUnstableEtcd" parameter to true under the unsupportedConfigOverrides section of the etcd CR. I have tried this and found that it can be used as a workaround, so to properly execute the DR scenario, this parameter should be set while executing the steps under step 4. It can be disabled afterwards.

Based on this, I believe that this might be a bug in the etcd operator: the IsSafeToUpdateRevision check should not be executed if there are only 2 etcd pods and the static pod definitions are not present on the third master node.

**Comment by tjungblu** [comment]
Hi @mbalazs,

we don't usually monitor the issues here, so please always open support tickets.

As per your discovery, yes, this is known and currently makes its way into the documentation for all versions:
https://github.com/openshift/openshift-docs/pull/54786

> Based on this, I believe that this might be a bug in the etcd operator: the IsSafeToUpdateRevision check should not be executed if there are only 2 etcd pods and the static pod definitions are not present on the third master node.

The challenge here is that the any operation that will touch the static pod definition will cause a rollout, which will eventually restart etcd. This causes downtime on the API and on etcd by violating quorum as taking down one of two pods will not allow you to get a raft proposal applied. 

That was a bug reported by a customer in 4.8, complaining about that exact downtime, and fixed last year around September, https://github.com/openshift/cluster-etcd-operator/pull/930 with 4.9 in here: https://github.com/openshift/cluster-etcd-operator/pull/912

So I'm quite curious why the procedure works with your 4.9 cluster? Which z release are you running there?

**Comment by mbalazs** [comment]
Hi @tjungblu,

I just wanted to let you know about this, I didn't know that this is a known issue - we are happy with this workaround, even more so if it will be the official documented way.

The 4.9 cluster is an old test cluster that we use for various tests like this and we don't update it on purpose, it is running 4.9.10 currently, so I hope this explains why the issue is not present there.

I am closing this issue then, since it is a known problem, and it is being handled in the documentation. Thanks for your reply.
